import Head from "next/head";
import Image from "next/image";
import useScale from "../hooks/useScale";
import styles from "../styles/Home.module.css";
import { RiDoubleQuotesL, RiDoubleQuotesR } from "react-icons/ri";
import { AiOutlineFile } from "react-icons/ai";
import { BsDownload } from "react-icons/bs";
import Button from "../components/button";
import domtoimage from "dom-to-image";
import { saveAs } from "file-saver";
export default function Home() {
  const { ref } = useScale();

  return (
    <div className="container">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="buttons">
        {/* <Button className="button-primary">
          Ozellestir <AiTwotoneSetting />
        </Button> */}
        <Button
          className="button-secondary"
          onClick={(e) => {
            document.querySelector(".post-form-submit").click();
          }}
        >
          Indir <BsDownload />
        </Button>
      </div>
      <div style={{ marginTop: "30pt" }}>Resim Kontrolleri</div>
      <div className="range-container">
        <div>
          Sağ Sol
          <input
            min={-100}
            max={200}
            defaultValue={50}
            type="range"
            onChange={(e) => {
              const img = document.querySelector("#img-preview");
              img.style.left = e.currentTarget.value + "%";
            }}
          />
        </div>
        <div>
          Yukarı Aşağı
          <input
            min={0}
            max={100}
            defaultValue={50}
            type="range"
            onChange={(e) => {
              const img = document.querySelector("#img-preview");
              img.style.top = e.currentTarget.value + "%";
            }}
          />
        </div>
        <div>
          Boyut
          <input
            min={0}
            max={100}
            defaultValue={50}
            type="range"
            onChange={(e) => {
              const img = document.querySelector("#img-preview");
              img.style.transform =
                "translate(-50%, -50%)" +
                " " +
                `scale(${e.currentTarget.value / 50})`;
            }}
          />
        </div>
      </div>
      <div className="theme-color">
        Tema Rengi{" "}
        <div>
          <input
            onChange={(e) => {
              document.documentElement.style.setProperty(
                "--theme-color",
                e.currentTarget.value
              );
            }}
            type="color"
            defaultValue="#1a3459"
          />
        </div>{" "}
      </div>

      <form
        onSubmit={(e) => {
          e.preventDefault();
          const node = document.querySelector(".post");
          const copy_node = node.cloneNode(true);

          document.body.appendChild(copy_node);
          copy_node.style.transform = "";
          domtoimage.toBlob(copy_node).then((blob) => {
            saveAs(blob, "damga.png");
            copy_node.style.visibility = "hidden";
            copy_node.remove();
          });
        }}
        className="post"
        ref={ref}
      >
        <button
          type="submit"
          className="post-form-submit"
          style={{ visibility: "hidden" }}
        />
        <div className="title">
          <span></span>
          MEKÜPTE
          <span></span>
        </div>
        <div className="post-author">
          <div className="author-image--container">
            <div className="author-image">
              <div className="img-container">
                <div className="file-uploader">
                  <input
                    required
                    type="file"
                    onChange={(e) => {
                      const files = e.currentTarget.files[0];
                      console.log(files);
                      if (!files) return;
                      const fileReader = new FileReader();
                      fileReader.readAsDataURL(files);
                      fileReader.addEventListener("load", (res) => {
                        document.querySelector("#img-preview").src =
                          res.target.result;
                      });
                    }}
                  />
                  <AiOutlineFile />
                </div>
                <img
                  style={{ transform: "transate(0,0) scale(1)" }}
                  id="img-preview"
                  accept="image/png, image/jpeg"
                ></img>
              </div>
            </div>
          </div>
          <input className="author-name" placeholder="Isim" required />
          <input className="author-date" placeholder="Tarih" required />
        </div>
        <div className="post-text">
          <RiDoubleQuotesL className="quote quote-start" />
          <textarea
            required
            placeholder="Yazi"
            onLoad={(e) => {
              e.currentTarget.style.height = e.currentTarget.scrollHeight;
            }}
            onChange={(e) => {
              e.currentTarget.style.height = "auto";
              e.currentTarget.style.height =
                e.currentTarget.scrollHeight + "px";
            }}
            className="text"
          />
          <RiDoubleQuotesR className="quote quote-end" />
        </div>
        <div className="post-number">
          #Damga <input required placeholder="0" type="number" />
        </div>
      </form>
    </div>
  );
}
